import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import DataStore from '@/context'

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
      <DataStore>{children}</DataStore>
      </body>
    </html>
  )
}
